### ISSUE TITLE
搜索异常

### ISSUE THREAD

**Issue by hezhiying** [taxusorg/xunsearch-laravel#1]
重现：
art tinker
Administrator::search('admin')->fuzzy()->range('id',1,100)->get() 正确
Administrator::search('ad')->fuzzy()->range('id',1,100)->get() 如下错误
再执行提示
XSException with message 'Broken server connection'

错误：
XSException with message 'Failed to recv the data from server completely (SIZE:0/8, REASON:closed)'
![image](https://user-images.githubusercontent.com/16780849/47279192-0b243100-d602-11e8-9643-449cf2e9a07f.png)

**Comment by taxusorg** [comment]
好的，我看看问题的原因。

前段时间升级到2.x之后一直在忙，没做过测试，抱歉。

Exception位置：

https://github.com/hightman/xs-sdk-php/blob/4f72a676188199d15d23f5fedc20c9c5a44135de/lib/XSServer.class.php#L429-L431

只能看出读取不到XunSearch连接的内容。

最好能提供一下你相关配置和`Administrator`中`xunSearchFieldsType`方法的内容，我好判断是哪个环节出的问题。谢谢。

**Comment by taxusorg** [comment]
好的，我看看问题的原因。

前段时间升级到2.x之后一直在忙，没做过测试，抱歉。

Exception位置：

https://github.com/hightman/xs-sdk-php/blob/4f72a676188199d15d23f5fedc20c9c5a44135de/lib/XSServer.class.php#L429-L431

只能看出读取不到XunSearch连接的内容。

最好能提供一下你相关配置和`Administrator`中`xunSearchFieldsType`方法的内容，我好判断是哪个环节出的问题。谢谢。

**Comment by taxusorg** [comment]
好的，我看看问题的原因。

前段时间升级到2.x之后一直在忙，没做过测试，抱歉。

Exception位置：

https://github.com/hightman/xs-sdk-php/blob/4f72a676188199d15d23f5fedc20c9c5a44135de/lib/XSServer.class.php#L429-L431

只能看出读取不到XunSearch连接的内容。

最好能提供一下你相关配置和`Administrator`中`xunSearchFieldsType`方法的内容，我好判断是哪个环节出的问题。谢谢。

**Comment by taxusorg** [comment]
没有找到错误。检查xunsearch的稳定性。

**Comment by hezhiying** [comment]
谢谢回复。

以下是Administrator的内容：

    public function xunSearchFieldsType()
    {
        return [
            'id' => [
                'type'=>self::XUNSEARCH_TYPE_NUMERIC,
            ],
            'username' => [
                'type'=>self::XUNSEARCH_TYPE_TITLE,
            ],
            'name' => [
                'type'=>self::XUNSEARCH_TYPE_BODY,
            ]
        ];
    }

我上面的问题只是出现在art tinker 模式中，在web中不会，我估计是在web中每次都会重联，而在tinker中就会出问题

**Comment by taxusorg** [comment]
只是 art tinker 模式的话，我过后再找时间处理。感谢反馈。
